// SPDX-FileCopyrightText: Copyright (c) 2025 InsilicAll. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// GENERATED by tools/semiempirical/gen_d_localframe.py from PYSEQM's vendored
// two_elec_two_center_int_local_frame_d_orbitals (BSD-3) -- DO NOT HAND-EDIT.
//
// Local-frame d-orbital two-center reduced two-electron integrals: analytic
// multipole-interaction expansion (Dewar-Thiel) for the YX case (d-atom A + sp
// atom B). Inputs are the interatomic distance r0 (bohr), the dipole/quadrupole/
// d charge separations and the additive rho radii; outputs the reduced integral
// vector consumed by the d-rotation + Fock assembly. Validated bit-exact against
// the oracle by tools/semiempirical/validate_d_localframe.py.

#ifndef NVMOLKIT_SEMIEMPIRICAL_D_LOCALFRAME_GENERATED_H
#define NVMOLKIT_SEMIEMPIRICAL_D_LOCALFRAME_GENERATED_H

#include <cmath>

#include "device_macros.h"

namespace nvMolKit {
namespace semiempirical {
namespace dlocal {

constexpr double kSemiEVlf = 27.21;


// YX: d-atom A + sp atom B. ri must hold 450 doubles.
NVMOLKIT_HD inline void riLocalYX(double r0, double da0, double db0, double qa0, double qb0, double dpa0, double dsa0, double dda0, double rho0a, double rho0b, double rho1a, double rho1b, double rho2a, double rho2b, double rho3a, double rho4a, double rho5a, double rho6a, double* ri) {
  const double ev = kSemiEVlf, ev1 = ev / 2.0, ev2 = ev / 4.0,
               ev3 = ev / 8.0, ev4 = ev / 16.0;
  const double kSqrt2 = 1.4142135623730951;
  auto sq = [](double x) { return x * x; };
  for (int i = 0; i < 450; ++i) ri[i] = 0.0;
  (void)ev4;
  double rhoSS = sq((rho0a+rho0b));
  double rhoSDD0 = sq((rho3a+rho0b));
  double rhoSSP = sq((rho1a+rho0b));
  double rhoSPD = sq((rho4a+rho0b));
  double rhoSPP = sq((rho2a+rho0b));
  double rhoSSD = sq((rho5a+rho0b));
  double rhoSDD = sq((rho6a+rho0b));
  double rhoDD0SP = sq((rho3a+rho1b));
  double rhoDD0PP = sq((rho3a+rho2b));
  double rhoSPSP = sq((rho1a+rho1b));
  double rhoSPPD = sq((rho4a+rho1b));
  double rhoSPPP = sq((rho2a+rho1b));
  double rhoSPSD = sq((rho5a+rho1b));
  double rhoSPDD = sq((rho6a+rho1b));
  double rhoPDPP = sq((rho4a+rho2b));
  double rhoPPPP = sq((rho2a+rho2b));
  double rhoPPDD = sq((rho6a+rho2b));
  double rhoPPSD = sq((rho5a+rho2b));
  double qq = ev/std::sqrt(sq(r0)+rhoSS);
  double DDq_Sq = ev/std::sqrt(sq(r0)+rhoSDD0);
  double Sq_SPUz = -(ev1/std::sqrt(sq((r0+db0))+rhoSSP)-ev1/std::sqrt(sq((r0-db0))+rhoSSP));
  double DDq_SPUz = -(ev1/std::sqrt(sq((r0+db0))+rhoDD0SP)-ev1/std::sqrt(sq((r0-db0))+rhoDD0SP));
  double DPUz_Sq = (ev1/std::sqrt(sq((r0+dpa0))+rhoSPD)-ev1/std::sqrt(sq((r0-dpa0))+rhoSPD));
  double SPUz_Sq = (ev1/std::sqrt(sq((r0+da0))+rhoSSP)-ev1/std::sqrt(sq((r0-da0))+rhoSSP));
  qb0 = qb0*kSqrt2;
  double Sq_PPQtzx_onehalfQtxy = ev2/std::sqrt(sq((r0-(2)*qb0))+rhoSPP)+ev2/std::sqrt(sq((r0+(2)*qb0))+rhoSPP)-ev1/std::sqrt(sq((r0))+sq(((0)*db0))+rhoSPP);
  double DDq_PPQtzx_onehalfQtxy = ev2/std::sqrt(sq((r0-qb0))+rhoDD0PP)+ev2/std::sqrt(sq((r0+qb0))+rhoDD0PP)-ev1/std::sqrt(sq((r0))+sq((qb0))+rhoDD0PP);
  double DDQtzx_onehalfQtxy_Sq = ev2/std::sqrt(sq((r0-dda0))+rhoSDD)+ev2/std::sqrt(sq((r0+dda0))+rhoSDD)-ev1/std::sqrt(sq((r0))+sq((dda0))+rhoSDD);
  double DSQtzx_onehalfQtxy_Sq = ev2/std::sqrt(sq((r0-dsa0))+rhoSSD)+ev2/std::sqrt(sq((r0+dsa0))+rhoSSD)-ev1/std::sqrt(sq((r0))+sq((dsa0))+rhoSSD);
  double PPQtzx_onehalfQtxy_Sq = ev2/std::sqrt(sq((r0-qa0))+rhoSPP)+ev2/std::sqrt(sq((r0+qa0))+rhoSPP)-ev1/std::sqrt(sq((r0))+sq((da0))+rhoSPP);
  qb0 = qb0/kSqrt2;
  double SPUpi_SPUpi = ev1/std::sqrt(sq(r0)+sq((da0-qb0))+rhoSPSP)-ev1/std::sqrt(sq(r0)+sq((da0+qb0))+rhoSPSP);
  double DPUpi_SPUpi = ev1/std::sqrt(sq(r0)+sq((db0-dpa0))+rhoSPPD)-ev1/std::sqrt(sq(r0)+sq((db0+dpa0))+rhoSPPD);
  double SPUz_SPUz = ev2/std::sqrt(sq((r0+da0-db0))+rhoSPSP) -  ev2/std::sqrt(sq((r0+da0+db0))+rhoSPSP) -  ev2/std::sqrt(sq((r0-da0-db0))+rhoSPSP) +  ev2/std::sqrt(sq((r0-da0+db0))+rhoSPSP);
  double DPUz_SPUz = ev2/std::sqrt(sq((r0+db0-dpa0))+rhoSPPD) -  ev2/std::sqrt(sq((r0+db0+dpa0))+rhoSPPD) -  ev2/std::sqrt(sq((r0-db0-dpa0))+rhoSPPD) +  ev2/std::sqrt(sq((r0-db0+dpa0))+rhoSPPD);
  dsa0 = dsa0/kSqrt2;
  dda0 = dda0/kSqrt2;
  double SPUpi_PPQpiz = -(-ev2/std::sqrt(sq((r0-qb0))+sq((da0-qb0))+rhoSPPP) +  ev2/std::sqrt(sq((r0-qb0))+sq((da0+qb0))+rhoSPPP) +  ev2/std::sqrt(sq((r0+qb0))+sq((da0-qb0))+rhoSPPP) -  ev2/std::sqrt(sq((r0+qb0))+sq((da0+qb0))+rhoSPPP));
  double DPUpi_PPQpiz = -(-ev2/std::sqrt(sq((r0-qb0))+sq((dpa0-qb0))+rhoPDPP) +  ev2/std::sqrt(sq((r0-qb0))+sq((dpa0+qb0))+rhoPDPP) +  ev2/std::sqrt(sq((r0+qb0))+sq((dpa0-qb0))+rhoPDPP) -  ev2/std::sqrt(sq((r0+qb0))+sq((dpa0+qb0))+rhoPDPP));
  double PPQpiz_SPUpi = (-ev2/std::sqrt(sq((r0-qa0))+sq((db0-qa0))+rhoSPPP) +  ev2/std::sqrt(sq((r0-qa0))+sq((db0+qa0))+rhoSPPP) +  ev2/std::sqrt(sq((r0+qa0))+sq((db0-qa0))+rhoSPPP) -  ev2/std::sqrt(sq((r0+qa0))+sq((db0+qa0))+rhoSPPP));
  double DSQpiz_SPUpi = (-ev2/std::sqrt(sq((r0-dsa0))+sq((db0-dsa0))+rhoSPSD) +  ev2/std::sqrt(sq((r0-dsa0))+sq((db0+dsa0))+rhoSPSD) +  ev2/std::sqrt(sq((r0+dsa0))+sq((db0-dsa0))+rhoSPSD) -  ev2/std::sqrt(sq((r0+dsa0))+sq((db0+dsa0))+rhoSPSD));
  double DDQpiz_SPUpi = (-ev2/std::sqrt(sq((r0-dda0))+sq((db0-dda0))+rhoSPDD) +  ev2/std::sqrt(sq((r0-dda0))+sq((db0+dda0))+rhoSPDD) +  ev2/std::sqrt(sq((r0+dda0))+sq((db0-dda0))+rhoSPDD) -  ev2/std::sqrt(sq((r0+dda0))+sq((db0+dda0))+rhoSPDD));
  dsa0 = dsa0*kSqrt2;
  dda0 = dda0*kSqrt2;
  qa0 = qa0*kSqrt2;
  qb0 = qb0*kSqrt2;
  double SPUz_PPQtzx_onehalfQtxy = (-ev3/std::sqrt(sq((r0-da0-1.0*qb0))+rhoSPPP) -  ev3/std::sqrt(sq((r0-da0+1.0*qb0))+rhoSPPP) +  ev3/std::sqrt(sq((r0+da0-1.0*qb0))+rhoSPPP) +  ev3/std::sqrt(sq((r0+da0+1.0*qb0))+rhoSPPP) +  ev2/std::sqrt(sq((r0-da0))+sq((1.0*qb0))+rhoSPPP) -  ev2/std::sqrt(sq((r0+da0))+sq((1.0*qb0))+rhoSPPP));
  double DPUz_PPQtzx_onehalfQtxy = (-ev3/std::sqrt(sq((r0-dpa0-1.0*qb0))+rhoPDPP) -  ev3/std::sqrt(sq((r0-dpa0+1.0*qb0))+rhoPDPP) +  ev3/std::sqrt(sq((r0+dpa0-1.0*qb0))+rhoPDPP) +  ev3/std::sqrt(sq((r0+dpa0+1.0*qb0))+rhoPDPP) +  ev2/std::sqrt(sq((r0-dpa0))+sq((1.0*qb0))+rhoPDPP) -  ev2/std::sqrt(sq((r0+dpa0))+sq((1.0*qb0))+rhoPDPP));
  double PPQtzx_onehalfQtxy_SPUz = -(-ev3/std::sqrt(sq((r0-db0-1.0*qa0))+rhoSPPP) -  ev3/std::sqrt(sq((r0-db0+1.0*qa0))+rhoSPPP) +  ev3/std::sqrt(sq((r0+db0-1.0*qa0))+rhoSPPP) +  ev3/std::sqrt(sq((r0+db0+1.0*qa0))+rhoSPPP) +  ev2/std::sqrt(sq((r0-db0))+sq((1.0*qa0))+rhoSPPP) -  ev2/std::sqrt(sq((r0+db0))+sq((1.0*qa0))+rhoSPPP));
  double DSQtzx_onehalfQtxy_SPUz = -(-ev3/std::sqrt(sq((r0-db0-1.0*dsa0))+rhoSPSD) -  ev3/std::sqrt(sq((r0-db0+1.0*dsa0))+rhoSPSD) +  ev3/std::sqrt(sq((r0+db0-1.0*dsa0))+rhoSPSD) +  ev3/std::sqrt(sq((r0+db0+1.0*dsa0))+rhoSPSD) +  ev2/std::sqrt(sq((r0-db0))+sq((1.0*dsa0))+rhoSPSD) -  ev2/std::sqrt(sq((r0+db0))+sq((1.0*dsa0))+rhoSPSD));
  double DDQtzx_onehalfQtxy_SPUz = -(-ev3/std::sqrt(sq((r0-db0-1.0*dda0))+rhoSPDD) -  ev3/std::sqrt(sq((r0-db0+1.0*dda0))+rhoSPDD) +  ev3/std::sqrt(sq((r0+db0-1.0*dda0))+rhoSPDD) +  ev3/std::sqrt(sq((r0+db0+1.0*dda0))+rhoSPDD) +  ev2/std::sqrt(sq((r0-db0))+sq((1.0*dda0))+rhoSPDD) -  ev2/std::sqrt(sq((r0+db0))+sq((1.0*dda0))+rhoSPDD));
  qa0 = qa0/kSqrt2;
  qb0 = qb0/kSqrt2;
  qb0 = qb0*kSqrt2;
  double PPQtzx_onehalfQtxy_PPQtzx_onehalfQtxy = (ev3/std::sqrt(sq(r0)+sq((qa0-qb0))+rhoPPPP) +  ev3/std::sqrt(sq(r0)+sq((qa0+qb0))+rhoPPPP) -  ev3/std::sqrt(sq((r0+qb0))+sq(qa0)+rhoPPPP) -  ev3/std::sqrt(sq((r0-qb0))+sq(qa0)+rhoPPPP) +  ev4/std::sqrt(sq((r0-qb0+qa0))+rhoPPPP) +  ev4/std::sqrt(sq((r0+qb0-qa0))+rhoPPPP) +  ev4/std::sqrt(sq((r0+qb0+qa0))+rhoPPPP) +  ev4/std::sqrt(sq((r0-qb0-qa0))+rhoPPPP) -  ev3/std::sqrt(sq((r0-qa0))+sq(qb0)+rhoPPPP) -  ev3/std::sqrt(sq((r0+qa0))+sq(qb0)+rhoPPPP))-  0.25*(ev2/std::sqrt(sq(r0)+sq((qa0-qb0))+rhoPPPP) + ev2/std::sqrt(sq(r0)+sq((qa0+qb0))+rhoPPPP) - ev1/std::sqrt(sq(r0)+sq(qa0)+sq(qb0)+rhoPPPP));
  double DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy = (ev3/std::sqrt(sq(r0)+sq((qb0-dsa0))+rhoPPSD) +  ev3/std::sqrt(sq(r0)+sq((qb0+dsa0))+rhoPPSD) -  ev3/std::sqrt(sq((r0+dsa0))+sq(qb0)+rhoPPSD) -  ev3/std::sqrt(sq((r0-dsa0))+sq(qb0)+rhoPPSD) +  ev4/std::sqrt(sq((r0-dsa0+qb0))+rhoPPSD) +  ev4/std::sqrt(sq((r0+dsa0-qb0))+rhoPPSD) +  ev4/std::sqrt(sq((r0+dsa0+qb0))+rhoPPSD) +  ev4/std::sqrt(sq((r0-dsa0-qb0))+rhoPPSD) -  ev3/std::sqrt(sq((r0-qb0))+sq(dsa0)+rhoPPSD) -  ev3/std::sqrt(sq((r0+qb0))+sq(dsa0)+rhoPPSD)) -   0.25*(ev2/std::sqrt(sq(r0)+sq((qb0-dsa0))+rhoPPSD) + ev2/std::sqrt(sq(r0)+sq((qb0+dsa0))+rhoPPSD) - ev1/std::sqrt(sq(r0)+sq(qb0)+sq(dsa0)+rhoPPSD));
  double DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy = (ev3/std::sqrt(sq(r0)+sq((qb0-dda0))+rhoPPDD) +  ev3/std::sqrt(sq(r0)+sq((qb0+dda0))+rhoPPDD) -  ev3/std::sqrt(sq((r0+dda0))+sq(qb0)+rhoPPDD) -  ev3/std::sqrt(sq((r0-dda0))+sq(qb0)+rhoPPDD) +  ev4/std::sqrt(sq((r0-dda0+qb0))+rhoPPDD) +  ev4/std::sqrt(sq((r0+dda0-qb0))+rhoPPDD) +  ev4/std::sqrt(sq((r0+dda0+qb0))+rhoPPDD) +  ev4/std::sqrt(sq((r0-dda0-qb0))+rhoPPDD) -  ev3/std::sqrt(sq((r0-qb0))+sq(dda0)+rhoPPDD) -  ev3/std::sqrt(sq((r0+qb0))+sq(dda0)+rhoPPDD))-  0.25*(ev2/std::sqrt(sq(r0)+sq((qb0-dda0))+rhoPPDD) + ev2/std::sqrt(sq(r0)+sq((qb0+dda0))+rhoPPDD) - ev1/std::sqrt(sq(r0)+sq(qb0)+sq(dda0)+rhoPPDD));
  qb0 = qb0/kSqrt2;
  dsa0 = dsa0/kSqrt2;
  dda0 = dda0/kSqrt2;
  double PPQpiz_PPQpiz = ev3/std::sqrt(sq((r0+qa0-qb0))+sq((qa0-qb0))+rhoPPPP) -  ev3/std::sqrt(sq((r0+qa0-qb0))+sq((qa0+qb0))+rhoPPPP) -  ev3/std::sqrt(sq((r0+qa0+qb0))+sq((qa0-qb0))+rhoPPPP) +  ev3/std::sqrt(sq((r0+qa0+qb0))+sq((qa0+qb0))+rhoPPPP) -  ev3/std::sqrt(sq((r0-qa0-qb0))+sq((qa0-qb0))+rhoPPPP) +  ev3/std::sqrt(sq((r0-qa0-qb0))+sq((qa0+qb0))+rhoPPPP) +  ev3/std::sqrt(sq((r0-qa0+qb0))+sq((qa0-qb0))+rhoPPPP) -  ev3/std::sqrt(sq((r0-qa0+qb0))+sq((qa0+qb0))+rhoPPPP);
  double DSQpiz_PPQpiz = ev3/std::sqrt(sq((r0+qb0-dsa0))+sq((qb0-dsa0))+rhoPPSD) -  ev3/std::sqrt(sq((r0+qb0-dsa0))+sq((qb0+dsa0))+rhoPPSD) -  ev3/std::sqrt(sq((r0+qb0+dsa0))+sq((qb0-dsa0))+rhoPPSD) +  ev3/std::sqrt(sq((r0+qb0+dsa0))+sq((qb0+dsa0))+rhoPPSD) -  ev3/std::sqrt(sq((r0-qb0-dsa0))+sq((qb0-dsa0))+rhoPPSD) +  ev3/std::sqrt(sq((r0-qb0-dsa0))+sq((qb0+dsa0))+rhoPPSD) +  ev3/std::sqrt(sq((r0-qb0+dsa0))+sq((qb0-dsa0))+rhoPPSD) -  ev3/std::sqrt(sq((r0-qb0+dsa0))+sq((qb0+dsa0))+rhoPPSD);
  double DDQpiz_PPQpiz = ev3/std::sqrt(sq((r0+qb0-dda0))+sq((qb0-dda0))+rhoPPDD) -  ev3/std::sqrt(sq((r0+qb0-dda0))+sq((qb0+dda0))+rhoPPDD) -  ev3/std::sqrt(sq((r0+qb0+dda0))+sq((qb0-dda0))+rhoPPDD) +  ev3/std::sqrt(sq((r0+qb0+dda0))+sq((qb0+dda0))+rhoPPDD) -  ev3/std::sqrt(sq((r0-qb0-dda0))+sq((qb0-dda0))+rhoPPDD) +  ev3/std::sqrt(sq((r0-qb0-dda0))+sq((qb0+dda0))+rhoPPDD) +  ev3/std::sqrt(sq((r0-qb0+dda0))+sq((qb0-dda0))+rhoPPDD) -  ev3/std::sqrt(sq((r0-qb0+dda0))+sq((qb0+dda0))+rhoPPDD);
  dsa0 = dsa0*kSqrt2;
  dda0 = dda0*kSqrt2;
  qb0 = qb0*kSqrt2;
  double PPQxy_PPQxy = ev2/std::sqrt(sq((r0))+sq((qa0-qb0))+rhoPPPP) +  ev2/std::sqrt(sq((r0))+sq((qa0+qb0))+rhoPPPP) -  ev1/std::sqrt(sq((r0))+sq((qa0))+sq((qb0))+rhoPPPP);
  double DSQxy_PPQxy = ev2/std::sqrt(sq((r0))+sq((qb0-dsa0))+rhoPPSD) +  ev2/std::sqrt(sq((r0))+sq((qb0+dsa0))+rhoPPSD) -  ev1/std::sqrt(sq((r0))+sq((qb0))+sq((dsa0))+rhoPPSD);
  double DDQxy_PPQxy = ev2/std::sqrt(sq((r0))+sq((qb0-dda0))+rhoPPDD) +  ev2/std::sqrt(sq((r0))+sq((qb0+dda0))+rhoPPDD) -  ev1/std::sqrt(sq((r0))+sq((qb0))+sq((dda0))+rhoPPDD);
  qb0 = qb0/kSqrt2;
  qb0 = qb0*kSqrt2;
  double tildaPPQxy_PPQxy = ev2/std::sqrt(sq((r0))+sq((qa0-qb0))+rhoPPPP) +  ev2/std::sqrt(sq((r0))+sq((qa0+qb0))+rhoPPPP) -  ev1/std::sqrt(sq((r0))+sq((qa0))+sq((qb0))+rhoPPPP);
  double tildaDSQxy_PPQxy = ev2/std::sqrt(sq((r0))+sq((qb0-dsa0))+rhoPPSD) +  ev2/std::sqrt(sq((r0))+sq((qb0+dsa0))+rhoPPSD) -  ev1/std::sqrt(sq((r0))+sq((qb0))+sq((dsa0))+rhoPPSD);
  double tildaDDQxy_PPQxy = ev2/std::sqrt(sq((r0))+sq((qb0-dda0))+rhoPPDD) +  ev2/std::sqrt(sq((r0))+sq((qb0+dda0))+rhoPPDD) -  ev1/std::sqrt(sq((r0))+sq((qb0))+sq((dda0))+rhoPPDD);
  qb0 = qb0/kSqrt2;
  ri[396] = tildaDSQxy_PPQxy*1.000000*1.000000;
  ri[308] = DPUpi_SPUpi*1.000000*1.000000;
  ri[353] = DPUpi_PPQpiz*1.000000*1.000000;
  ri[174] = DPUpi_SPUpi*1.000000*1.000000;
  ri[219] = DPUpi_PPQpiz*1.000000*1.000000;
  ri[44] = DDq_Sq*1.000000*1.000000+DDQtzx_onehalfQtxy_Sq*-1.333333*1.000000;
  ri[269] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*-0.666667+DDQtzx_onehalfQtxy_Sq*-1.333333*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*-1.333333*-0.666667;
  ri[449] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*-0.666667+DDQtzx_onehalfQtxy_Sq*-1.333333*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*-1.333333*-0.666667;
  ri[89] = DDq_SPUz*1.000000*1.000000+DDQtzx_onehalfQtxy_SPUz*-1.333333*1.000000;
  ri[134] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*1.333333+DDQtzx_onehalfQtxy_Sq*-1.333333*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*-1.333333*1.333333;
  ri[150] = DSQpiz_SPUpi*1.000000*1.000000;
  ri[195] = DSQpiz_PPQpiz*1.000000*1.000000;
  ri[17] = DPUz_Sq*1.000000*1.000000;
  ri[242] = DPUz_Sq*1.000000*1.000000+DPUz_PPQtzx_onehalfQtxy*1.000000*-0.666667;
  ri[422] = DPUz_Sq*1.000000*1.000000+DPUz_PPQtzx_onehalfQtxy*1.000000*-0.666667;
  ri[62] = DPUz_SPUz*1.000000*1.000000;
  ri[107] = DPUz_Sq*1.000000*1.000000+DPUz_PPQtzx_onehalfQtxy*1.000000*1.333333;
  ri[151] = DPUpi_SPUpi*1.000000*1.000000;
  ri[196] = DPUpi_PPQpiz*1.000000*1.000000;
  ri[311] = DDQpiz_SPUpi*1.000000*1.000000;
  ri[356] = DDQpiz_PPQpiz*1.000000*1.000000;
  ri[20] = DDq_Sq*1.000000*1.000000+DDQtzx_onehalfQtxy_Sq*0.666667*1.000000;
  ri[245] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*-0.666667+DDQtzx_onehalfQtxy_Sq*0.666667*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*0.666667*-0.666667+DDQxy_PPQxy*1.000000*1.000000;
  ri[425] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*-0.666667+DDQtzx_onehalfQtxy_Sq*0.666667*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*0.666667*-0.666667-DDQxy_PPQxy*1.000000*1.000000;
  ri[65] = DDq_SPUz*1.000000*1.000000+DDQtzx_onehalfQtxy_SPUz*0.666667*1.000000;
  ri[110] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*1.333333+DDQtzx_onehalfQtxy_Sq*0.666667*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*0.666667*1.333333;
  ri[10] = DSQtzx_onehalfQtxy_Sq*1.154701*1.000000;
  ri[235] = DSQtzx_onehalfQtxy_Sq*1.154701*1.000000+DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*1.154701*-0.666667;
  ri[415] = DSQtzx_onehalfQtxy_Sq*1.154701*1.000000+DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*1.154701*-0.666667;
  ri[55] = DSQtzx_onehalfQtxy_SPUz*1.154701*1.000000;
  ri[100] = DSQtzx_onehalfQtxy_Sq*1.154701*1.000000+DSQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*1.154701*1.333333;
  ri[147] = DPUpi_SPUpi*-0.577350*1.000000;
  ri[192] = DPUpi_PPQpiz*-0.577350*1.000000;
  ri[283] = DPUpi_SPUpi*1.000000*1.000000*-0.577350;
  ri[328] = -DPUpi_PPQpiz*1.000000*1.000000*0.57735026918962995;
  ri[11] = DPUz_Sq*1.154701*1.000000;
  ri[236] = DPUz_Sq*1.154701*1.000000+DPUz_PPQtzx_onehalfQtxy*1.154701*-0.666667;
  ri[416] = DPUz_Sq*1.154701*1.000000+DPUz_PPQtzx_onehalfQtxy*1.154701*-0.666667;
  ri[56] = DPUz_SPUz*1.154701*1.000000;
  ri[101] = DPUz_Sq*1.154701*1.000000+DPUz_PPQtzx_onehalfQtxy*1.154701*1.333333;
  ri[400] = tildaDDQxy_PPQxy*1.000000*1.000000*1.1547005383793001;
  ri[154] = DDQpiz_SPUpi*0.577350*1.000000;
  ri[199] = DDQpiz_PPQpiz*0.577350*1.000000;
  ri[14] = DDq_Sq*1.000000*1.000000+DDQtzx_onehalfQtxy_Sq*1.333333*1.000000;
  ri[239] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*-0.666667+DDQtzx_onehalfQtxy_Sq*1.333333*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*1.333333*-0.666667;
  ri[419] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*-0.666667+DDQtzx_onehalfQtxy_Sq*1.333333*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*1.333333*-0.666667;
  ri[59] = DDq_SPUz*1.000000*1.000000+DDQtzx_onehalfQtxy_SPUz*1.333333*1.000000;
  ri[104] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*1.333333+DDQtzx_onehalfQtxy_Sq*1.333333*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*1.333333*1.333333;
  ri[291] = DSQpiz_SPUpi*1.000000*1.000000;
  ri[336] = DSQpiz_PPQpiz*1.000000*1.000000;
  ri[24] = DPUz_Sq*1.000000*1.000000;
  ri[249] = DPUz_Sq*1.000000*1.000000+DPUz_PPQtzx_onehalfQtxy*1.000000*-0.666667;
  ri[429] = DPUz_Sq*1.000000*1.000000+DPUz_PPQtzx_onehalfQtxy*1.000000*-0.666667;
  ri[69] = DPUz_SPUz*1.000000*1.000000;
  ri[114] = DPUz_Sq*1.000000*1.000000+DPUz_PPQtzx_onehalfQtxy*1.000000*1.333333;
  ri[292] = DPUpi_SPUpi*1.000000*1.000000;
  ri[337] = DPUpi_PPQpiz*1.000000*1.000000;
  ri[177] = DDQpiz_SPUpi*1.000000*1.000000;
  ri[222] = DDQpiz_PPQpiz*1.000000*1.000000;
  ri[386] = tildaDDQxy_PPQxy*1.000000*1.000000;
  ri[295] = DDQpiz_SPUpi*1.000000*1.000000*0.57735026918962995;
  ri[340] = DDQpiz_PPQpiz*1.000000*1.000000*0.57735026918962995;
  ri[27] = DDq_Sq*1.000000*1.000000+DDQtzx_onehalfQtxy_Sq*0.666667*1.000000;
  ri[252] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*-0.666667+DDQtzx_onehalfQtxy_Sq*0.666667*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*0.666667*-0.666667-DDQxy_PPQxy*1.000000*1.000000;
  ri[432] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*-0.666667+DDQtzx_onehalfQtxy_Sq*0.666667*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*0.666667*-0.666667+DDQxy_PPQxy*1.000000*1.000000;
  ri[72] = DDq_SPUz*1.000000*1.000000+DDQtzx_onehalfQtxy_SPUz*0.666667*1.000000;
  ri[117] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*1.333333+DDQtzx_onehalfQtxy_Sq*0.666667*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*0.666667*1.333333;
  ri[253] = DSQxy_PPQxy*1.000000*1.000000;
  ri[433] = -DSQxy_PPQxy*1.000000*1.000000;
  ri[165] = DPUpi_SPUpi*1.000000*1.000000;
  ri[210] = DPUpi_PPQpiz*1.000000*1.000000;
  ri[301] = -DPUpi_SPUpi*1.000000*1.000000;
  ri[346] = -DPUpi_PPQpiz*1.000000*1.000000;
  ri[168] = DDQpiz_SPUpi*1.000000*1.000000;
  ri[213] = DDQpiz_PPQpiz*1.000000*1.000000;
  ri[257] = DDQxy_PPQxy*1.154701*1.000000;
  ri[437] = -DDQxy_PPQxy*1.154701*1.000000;
  ri[304] = -DDQpiz_SPUpi*1.000000*1.000000;
  ri[349] = -DDQpiz_PPQpiz*1.000000*1.000000;
  ri[35] = DDq_Sq*1.000000*1.000000+DDQtzx_onehalfQtxy_Sq*-1.333333*1.000000;
  ri[260] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*-0.666667+DDQtzx_onehalfQtxy_Sq*-1.333333*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*-1.333333*-0.666667;
  ri[440] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*-0.666667+DDQtzx_onehalfQtxy_Sq*-1.333333*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*-1.333333*-0.666667;
  ri[80] = DDq_SPUz*1.000000*1.000000+DDQtzx_onehalfQtxy_SPUz*-1.333333*1.000000;
  ri[125] = DDq_Sq*1.000000*1.000000+DDq_PPQtzx_onehalfQtxy*1.000000*1.333333+DDQtzx_onehalfQtxy_Sq*-1.333333*1.000000+DDQtzx_onehalfQtxy_PPQtzx_onehalfQtxy*-1.333333*1.333333;
}

}  // namespace dlocal
}  // namespace semiempirical
}  // namespace nvMolKit

#endif  // NVMOLKIT_SEMIEMPIRICAL_D_LOCALFRAME_GENERATED_H
