// SPDX-FileCopyrightText: Copyright (c) 2025 InsilicAll. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// GENERATED by tools/semiempirical/gen_pm6_hof_ref.py (calibrated against MOPAC
// 23.2.5 PM6) -- DO NOT HAND-EDIT.
//
// Per-element heat-of-formation reference for the canonical (MOPAC-aligned) PM6
// heat of formation: HoF(kcal) = kEvToKcal * (E_elec + E_core_PWCCT) - sum kHofRef.
// Each kHofRef[Z] = kEvToKcal*EISOL - EHEAT, fit by least squares. The light/halide
// refs [1,6,7,8,9,15,16,17,35,53] are fit on simple hydrides (<0.1 kcal/mol). The
// added main-group/metal refs [5,13,14,30,31,32,48,50,80] (B, Al, Si, Zn, Ga, Ge,
// Cd, Sn, Hg) are fit with the light refs held fixed, on metal halides/hydrides/
// methyls, and reproduce MOPAC PM6 HoF to <=1.2 kcal/mol per compound. With the
// PWCCT core-core (bit-exact to MOPAC) and the PYSEQM electronic SCF, the HoF then
// matches MOPAC PM6 to ~1 kcal/mol for light + Br molecules (iodine looser).

#ifndef NVMOLKIT_SEMIEMPIRICAL_PWCCT_REF_DATA_H
#define NVMOLKIT_SEMIEMPIRICAL_PWCCT_REF_DATA_H

#include "pwcct_data.h"  // kPwcctMaxZ

namespace nvMolKit {
namespace semiempirical {
namespace pwcct {

constexpr double kEvToKcal = 23.060548;

// kHofRef[Z] (kcal/mol); unsupported elements are 0.
constexpr double kHofRef[kPwcctMaxZ + 1] = {
    0.0,
    -311.476506666258,  // 1 H
    0.0,
    0.0,
    0.0,
    -1277.0509206233398,  // 5 B
    -2827.2283072936534,  // 6 C
    -4147.26932700559,  // 7 N
    -6680.73353796695,  // 8 O
    -10814.786351243965,  // 9 F
    0.0,
    0.0,
    0.0,
    -1186.9660190768207,  // 13 Al
    -1685.5568390624558,  // 14 Si
    -3296.2004726280197,  // 15 P
    -4026.764120401334,  // 16 S
    -5861.062212826418,  // 17 Cl
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    -662.2118215691428,  // 30 Zn
    -1383.190583291038,  // 31 Ga
    -1856.627398337635,  // 32 Ge
    0.0,
    0.0,
    -5260.524490849857,  // 35 Br
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    -548.0807424562862,  // 48 Cd
    0.0,
    -1716.3471434989226,  // 50 Sn
    0.0,
    0.0,
    -5747.441387420949,  // 53 I
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    -679.7356408184984,  // 80 Hg
};

}  // namespace pwcct
}  // namespace semiempirical
}  // namespace nvMolKit

#endif  // NVMOLKIT_SEMIEMPIRICAL_PWCCT_REF_DATA_H
