"""Bake the PM6 pairwise core-core (PWCCT) parameters for the supported elements.

The canonical PM6 (Stewart 2007, as in MOPAC) replaces the AM1-style core-core
repulsion with a Pairwise Core-Core Term: per element a monopole radius (pcore)
and a single unpolarizable-core Gaussian (a, b, c), and per element PAIR two
parameters (x, alpha). Our PYSEQM-derived engine reproduces MOPAC's electronic
structure bit-closely (charges + eigenvalues match), so swapping the core-core to
PWCCT is what aligns the energy / heat of formation with canonical PM6 / MOPAC.

The light/halide elements [1,6,7,8,9,15,16,17,35,53] are taken from SCINE Sparrow's
PM6 resource (BSD-3-Clause, github.com/qcscine/Sparrow,
src/Sparrow/Sparrow/Resources/Pm6/parameters.json), which encodes Stewart's
published PM6 parameters; MOPAC is the verification oracle.

The additional main-group/metal elements [5,13,14,30,31,32,48,50,80]
(B, Al, Si, Zn, Ga, Ge, Cd, Sn, Hg) are sourced directly from MOPAC 23.2.5's own
PM6 parameters and embedded in data/pm6_pwcct_mopac_extra.json: per element the
PO9 monopole radius (bohr) and the guess1/2/3 unpolarizable-core Gaussian (printed
by MOPAC under "PARAMETER VALUES USED ..." with the HCORE keyword), and per pair
the alpb/xfac diatomic factors (from MOPAC's parameters_for_PM6_C.F90). With these,
the PWCCT core-core reproduces MOPAC's NUCLEAR-NUCLEAR REPULSION bit-exactly for
these elements too (see validate_pwcct.py / validate_pm6d_hof_pwcct.py).

    # one-time: download Sparrow's PM6 parameters.json
    curl -sL https://raw.githubusercontent.com/qcscine/Sparrow/master/src/Sparrow/\\
Sparrow/Resources/Pm6/parameters.json -o /tmp/pm6par.json
    SPARROW_PM6_PARAMS=/tmp/pm6par.json \\
      python3 tools/semiempirical/gen_pm6_pwcct_header.py

Writes rocmolkit/src/semiempirical/pwcct_data.h (do not hand-edit).
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
OUT = ROOT / "rocmolkit" / "src" / "semiempirical" / "pwcct_data.h"
# MOPAC-sourced extra elements (B, Al, Si, Zn, Ga, Ge, Cd, Sn, Hg) embedded as JSON.
MOPAC_EXTRA = Path(__file__).resolve().parent / "data" / "pm6_pwcct_mopac_extra.json"
SPARROW_ELEMS = [1, 6, 7, 8, 9, 15, 16, 17, 35, 53]  # from Sparrow parameters.json
EXTRA_ELEMS = [5, 13, 14, 30, 31, 32, 48, 50, 80]     # from MOPAC (data file above)
ELEMS = sorted(SPARROW_ELEMS + EXTRA_ELEMS)
MAXZ = 80  # bumped to include Hg (Z=80); the NaN guard still gates uncalibrated Z

HEADER = """// SPDX-FileCopyrightText: Copyright (c) 2025 InsilicAll. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// GENERATED by tools/semiempirical/gen_pm6_pwcct_header.py from SCINE Sparrow's
// PM6 parameters.json (BSD-3-Clause; Stewart 2007 PM6) -- DO NOT HAND-EDIT.
//
// PM6 pairwise core-core (PWCCT) parameters, sliced to the supported elements.
// Per element: pcore (monopole radius, bohr) and one Gaussian core term (a, b, c).
// Per element pair: x and alpha. Universal constants below are already converted
// to atomic units (bohr), matching Sparrow/Stewart.

#ifndef NVMOLKIT_SEMIEMPIRICAL_PWCCT_DATA_H
#define NVMOLKIT_SEMIEMPIRICAL_PWCCT_DATA_H

namespace nvMolKit {
namespace semiempirical {
namespace pwcct {

constexpr int kPwcctMaxZ = %(MAXZ)d;

// Per-element / per-pair data. pcore is the monopole radius in bohr; x / alpha are
// the per-pair parenthesis parameters (alpha in Angstrom^-1, paper units); the
// Gaussian (a, b, c) is the per-element unpolarizable-core term. The universal PM6
// constants live in pwcct_device.h (paper eV/Angstrom convention).
""" % {"MAXZ": MAXZ}

FOOTER = """
}  // namespace pwcct
}  // namespace semiempirical
}  // namespace nvMolKit

#endif  // NVMOLKIT_SEMIEMPIRICAL_PWCCT_DATA_H
"""


def main() -> int:
    src = os.environ.get("SPARROW_PM6_PARAMS", "/tmp/pm6par.json")
    if not Path(src).is_file():
        sys.exit(f"Sparrow PM6 parameters.json not found at {src} "
                 "(set SPARROW_PM6_PARAMS; see module docstring)")
    d = json.loads(Path(src).read_text())
    atomic = {e["key"]: e["value"] for e in d["atomic"]}
    pairs = {}
    for e in d["diatomic"]:
        a, b = e["key"]["first"], e["key"]["second"]
        pairs[(a, b)] = (e["value"]["factor"], e["value"]["exponent"])

    nz = MAXZ + 1
    pcore = ["0.0"] * nz
    ga = ["0.0"] * nz
    gb = ["0.0"] * nz
    gc = ["0.0"] * nz
    for z in SPARROW_ELEMS:
        v = atomic[z]
        pcore[z] = repr(float(v["pack"]["pcore"]))
        g = v.get("gaussianRepulsion", [])
        if g:  # at most one term across PM6
            ga[z] = repr(float(g[0]["a"]))
            gb[z] = repr(float(g[0]["b"]))
            gc[z] = repr(float(g[0]["c"]))

    # symmetric pair tables x[zi*nz+zj], alpha[..] (Sparrow, light/halide pairs)
    xt = ["0.0"] * (nz * nz)
    at = ["0.0"] * (nz * nz)
    for zi in SPARROW_ELEMS:
        for zj in SPARROW_ELEMS:
            p = pairs.get((zi, zj)) or pairs.get((zj, zi))
            if p is not None:
                xt[zi * nz + zj] = repr(float(p[0]))
                at[zi * nz + zj] = repr(float(p[1]))

    # Layer in the MOPAC-sourced extra elements (B, Al, Si, Zn, Ga, Ge, Cd, Sn, Hg):
    # per-element PO9 (= pcore, bohr) and guess Gaussian, and every pair that
    # involves an extra element (alpb/xfac). Baked Sparrow-Sparrow pairs are left
    # untouched, matching the as-shipped header.
    extra = json.loads(MOPAC_EXTRA.read_text())
    for zs, e in extra["elem"].items():
        z = int(zs)
        pcore[z] = repr(float(e["pcore"]))
        if e.get("gauss"):
            ga[z] = repr(float(e["gauss"][0]))
            gb[z] = repr(float(e["gauss"][1]))
            gc[z] = repr(float(e["gauss"][2]))
    for key, (x, a) in extra["pairs"].items():  # stored once as "i,j" with i >= j
        zi, zj = (int(t) for t in key.split(","))
        xt[zi * nz + zj] = xt[zj * nz + zi] = repr(float(x))
        at[zi * nz + zj] = at[zj * nz + zi] = repr(float(a))

    out = [HEADER]
    out.append(f"\nconstexpr double kPcore[kPwcctMaxZ + 1] = {{{', '.join(pcore)}}};\n")
    out.append(f"constexpr double kGaussA[kPwcctMaxZ + 1] = {{{', '.join(ga)}}};\n")
    out.append(f"constexpr double kGaussB[kPwcctMaxZ + 1] = {{{', '.join(gb)}}};\n")
    out.append(f"constexpr double kGaussC[kPwcctMaxZ + 1] = {{{', '.join(gc)}}};\n\n")
    out.append("// Per-pair x / alpha, symmetric, indexed [zi*(kPwcctMaxZ+1)+zj].\n")
    out.append(f"constexpr double kPairX[(kPwcctMaxZ + 1) * (kPwcctMaxZ + 1)] = {{{', '.join(xt)}}};\n")
    out.append(f"constexpr double kPairAlpha[(kPwcctMaxZ + 1) * (kPwcctMaxZ + 1)] = {{{', '.join(at)}}};\n")
    out.append(FOOTER)
    OUT.write_text("".join(out))
    print(f"wrote {OUT.relative_to(ROOT)}  (elements {ELEMS}, "
          f"{sum(1 for x in xt if x != '0.0')} pair entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
