"""Generate rocmolkit/src/semiempirical/pm6_params_data.h from the PM6 CSV.

Bakes the public PM6 (Stewart/MOPAC) parameters into a C++ constant table so
the library has no runtime data-file dependency. Run from the repo root after
editing the CSV:

    python3 tools/semiempirical/gen_pm6_params_header.py

Keep the struct field order here in sync with struct Pm6ElementParams in
pm6_params.h.
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CSV = ROOT / "tools" / "semiempirical" / "data" / "pm6_params_mopac.csv"
OUT = ROOT / "rocmolkit" / "src" / "semiempirical" / "pm6_params_data.h"

# Scalar CSV columns in struct order (after Z), excluding the 4-wide Gaussian
# arrays and the trailing z_s/z_p/z_d which we emit explicitly.
SCALAR = [
    "U_ss", "U_pp", "U_dd", "zeta_s", "zeta_p", "zeta_d",
    "beta_s", "beta_p", "beta_d", "s_orb_exp_tail", "p_orb_exp_tail",
    "d_orb_exp_tail", "g_ss", "g_sp", "g_pp", "g_p2", "h_sp",
    "F0SD", "G2SD", "rho_core", "alpha", "EISOL",
]


def _f(row: dict, key: str) -> str:
    val = (row.get(key) or "").strip()
    if not val:
        return "0.0"
    # One upstream row (Re, Z=75, unused) has a missing comma that merges two
    # cells into one whitespace-separated field; take the first numeric token.
    return repr(float(val.split()[0]))


def main() -> None:
    rows = []
    with CSV.open() as fh:
        for raw in csv.DictReader(fh):
            row = {k.strip(): v for k, v in raw.items()}
            z = int(row["N"])
            scal = ", ".join(_f(row, k) for k in SCALAR)
            gk = ", ".join(_f(row, f"Gaussian{i}_K") for i in range(1, 5))
            gl = ", ".join(_f(row, f"Gaussian{i}_L") for i in range(1, 5))
            gm = ", ".join(_f(row, f"Gaussian{i}_M") for i in range(1, 5))
            zsz = ", ".join(_f(row, k) for k in ("z_s", "z_p", "z_d"))
            rows.append(
                f"    {{{z:>3}, {scal}, "
                f"{{{gk}}}, {{{gl}}}, {{{gm}}}, {zsz}}},  // {row['sym'].strip()}"
            )

    body = "\n".join(rows)
    OUT.write_text(
        "// SPDX-FileCopyrightText: Copyright (c) 2025 InsilicAll. All rights reserved.\n"
        "// SPDX-License-Identifier: Apache-2.0\n"
        "//\n"
        "// GENERATED by tools/semiempirical/gen_pm6_params_header.py from\n"
        "// tools/semiempirical/data/pm6_params_mopac.csv (public PM6/MOPAC params).\n"
        "// Do not edit by hand — regenerate from the CSV.\n\n"
        "#ifndef NVMOLKIT_SEMIEMPIRICAL_PM6_PARAMS_DATA_H\n"
        "#define NVMOLKIT_SEMIEMPIRICAL_PM6_PARAMS_DATA_H\n\n"
        '#include "pm6_params.h"\n\n'
        "namespace nvMolKit {\n"
        "namespace semiempirical {\n\n"
        "// clang-format off\n"
        "static const Pm6ElementParams kPm6Params[] = {\n"
        f"{body}\n"
        "};\n"
        "// clang-format on\n\n"
        "static const int kNumPm6Params = sizeof(kPm6Params) / sizeof(kPm6Params[0]);\n\n"
        "}  // namespace semiempirical\n"
        "}  // namespace nvMolKit\n\n"
        "#endif  // NVMOLKIT_SEMIEMPIRICAL_PM6_PARAMS_DATA_H\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} elements)")


if __name__ == "__main__":
    main()
