"""Bake the PM6-D3 dispersion reference data for the supported elements.

The PM6-D3H4 dispersion (Grimme D3, zero-damping, s8=0 so only the C6/e6 term is
active) needs, per element pair, the reference C6 table (c6ab), the cutoff radii
(r0ab), the reference-count (mxc) and the covalent radii (rcov). The full table is
94x94x5x5x3; here we slice it to the main-group elements rocMolKit's PM6_D engine
supports (H, C, N, O, F, P, S, Cl, Br, I) and emit a compact C++ constant header,
mirroring how onecenter_d_data.h is generated.

    MLXMOLKIT=/tmp/mlxmolkit_inspect/mlxmolkit \\
      /tmp/semienv/bin/python tools/semiempirical/gen_d3_header.py

Writes rocmolkit/src/semiempirical/d3_data.h (do not hand-edit).
"""

from __future__ import annotations

import os
import sys
import types
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent.parent
OUT = ROOT / "rocmolkit" / "src" / "semiempirical" / "d3_data.h"
ELEMS = [1, 6, 7, 8, 9, 15, 16, 17, 35, 53]
MAXZ = 53

HEADER = """// SPDX-FileCopyrightText: Copyright (c) 2025 InsilicAll. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// GENERATED by tools/semiempirical/gen_d3_header.py from PYSEQM/mlxmolkit's D3
// reference data (Grimme D3, BSD-3) -- DO NOT HAND-EDIT.
//
// PM6-D3 dispersion reference data, sliced to the main-group elements the PM6_D
// engine supports. Indexed by atomic number (1-based) up to kD3MaxZ; unsupported
// entries are zero. c6ab is [Z][Z][mxc][mxc][3] (C6, CN_i, CN_j). With s8=0 in
// PM6-D3H4 only the C6/e6 term is active.

#ifndef NVMOLKIT_SEMIEMPIRICAL_D3_DATA_H
#define NVMOLKIT_SEMIEMPIRICAL_D3_DATA_H

namespace nvMolKit {
namespace semiempirical {
namespace d3 {

constexpr int kD3MaxZ = %(MAXZ)d;
constexpr int kD3MaxC = 5;
""" % {"MAXZ": MAXZ}

FOOTER = """
}  // namespace d3
}  // namespace semiempirical
}  // namespace nvMolKit

#endif  // NVMOLKIT_SEMIEMPIRICAL_D3_DATA_H
"""


def main() -> int:
    mlx = os.environ.get("MLXMOLKIT")
    if not mlx or not os.path.isdir(mlx):
        sys.exit("set MLXMOLKIT to the cloned mlxmolkit package dir")
    for name in ("mlx", "mlx.core"):
        sys.modules[name] = types.ModuleType(name)
    sys.modules["mlx"].core = sys.modules["mlx.core"]
    sys.path.insert(0, mlx)
    import importlib
    D = importlib.import_module("rm1.pm6_d3h4")
    c6ab, mxc = D._load_c6ab()
    r0ab = D._load_r0ab()
    rcov = np.asarray(D.RCOV, dtype=np.float64)

    # Flatten c6ab[Z1][Z2][i][j][0:3] for 1..MAXZ (1-based -> store [Z*..]).
    nz = MAXZ + 1
    flat = []
    for z1 in range(1, nz):
        for z2 in range(1, nz):
            for i in range(5):
                for j in range(5):
                    for k in range(3):
                        if z1 in ELEMS and z2 in ELEMS:
                            flat.append(float(c6ab[z1 - 1, z2 - 1, i, j, k]))
                        else:
                            flat.append(0.0)

    out = [HEADER]
    out.append("constexpr double kPM6D3_s6 = 0.880, kPM6D3_rs6 = 1.180, kPM6D3_alp6 = 22.0;\n")
    out.append("constexpr double kD3Bohr = 0.5291772083, kD3AuToKcal = 627.5094740631;\n\n")

    mxc_v = ", ".join(str(int(mxc[z - 1])) if z in ELEMS else "0" for z in range(1, nz))
    out.append(f"constexpr int kD3Mxc[kD3MaxZ + 1] = {{0, {mxc_v}}};\n\n")

    rcov_v = ", ".join(repr(float(rcov[z - 1])) if z in ELEMS else "0.0" for z in range(1, nz))
    out.append(f"constexpr double kD3Rcov[kD3MaxZ + 1] = {{0.0, {rcov_v}}};\n\n")

    r0_v = []
    for z1 in range(1, nz):
        for z2 in range(1, nz):
            r0_v.append(repr(float(r0ab[z1 - 1, z2 - 1])) if (z1 in ELEMS and z2 in ELEMS) else "0.0")
    out.append(f"constexpr double kD3R0ab[(kD3MaxZ + 1) * (kD3MaxZ + 1)] = {{")
    # row 0 padding + each (z1,z2): we store as a flat [(MAXZ+1)^2] with 1-based z.
    full = ["0.0"] * (nz * nz)
    idx = 0
    for z1 in range(1, nz):
        for z2 in range(1, nz):
            full[z1 * nz + z2] = r0_v[idx]
            idx += 1
    out.append(", ".join(full))
    out.append("};\n\n")

    out.append("// c6ab[((Z1*kD3MaxC + i)*kD3MaxC + j) ...]: flat [(MAXZ+1)^2 * 5*5*3].\n")
    out.append(f"constexpr double kD3C6ab[(kD3MaxZ + 1) * (kD3MaxZ + 1) * 5 * 5 * 3] = {{")
    # build full flat with 1-based z padding
    fullc = [0.0] * (nz * nz * 75)
    idx = 0
    for z1 in range(1, nz):
        for z2 in range(1, nz):
            for t in range(75):
                fullc[(z1 * nz + z2) * 75 + t] = flat[idx]
                idx += 1
    out.append(", ".join(repr(x) for x in fullc))
    out.append("};\n")
    out.append(FOOTER)

    OUT.write_text("".join(out))
    print(f"wrote {OUT.relative_to(ROOT)}  (elements {ELEMS})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
