"""Calibrate the canonical PM6 heat-of-formation reference against MOPAC.

The canonical PM6 heat of formation is HoF = kEvToKcal*(E_elec + E_core_PWCCT) -
sum_atoms kHofRef[Z], where kHofRef[Z] = kEvToKcal*EISOL - EHEAT for the element.
Rather than recomputing MOPAC's EISOL from the atomic reference configuration, we
fit kHofRef by least squares so the simple hydrides (one heavy atom + H, where the
PYSEQM electronic structure is closest to MOPAC) reproduce MOPAC's own FINAL HEAT
OF FORMATION. MOPAC 23.2.5 is the oracle.

Requires a built MOPAC (set MOPAC_DIR to the unpacked mopac-*-linux dir, which has
bin/mopac and lib/) and a venv with numpy.

    MOPAC_DIR=/tmp/mopac_bin/mopac-23.2.5-linux \\
      /tmp/semienv/bin/python tools/semiempirical/gen_pm6_hof_ref.py

Rewrites rocmolkit/src/semiempirical/pwcct_ref_data.h (do not hand-edit).
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent.parent
SRC = ROOT / "rocmolkit" / "src" / "semiempirical"
OUT = SRC / "pwcct_ref_data.h"
SYM = {1: "H", 6: "C", 7: "N", 8: "O", 9: "F", 15: "P", 16: "S", 17: "Cl", 35: "Br", 53: "I"}
CONV = 23.060548

# Calibration set: simple closed-shell hydrides (+ H2/Cl2) covering every element.
CAL = {
    "H2": ([1, 1], [[0, 0, 0], [0, 0, 0.74]]),
    "CH4": ([6, 1, 1, 1, 1], [[0, 0, 0], [0.629, 0.629, 0.629], [-0.629, -0.629, 0.629],
                              [-0.629, 0.629, -0.629], [0.629, -0.629, -0.629]]),
    "NH3": ([7, 1, 1, 1], [[0, 0, 0], [0.94, 0, 0.33], [-0.47, 0.81, 0.33], [-0.47, -0.81, 0.33]]),
    "H2O": ([8, 1, 1], [[0, 0, 0], [0.757, 0, 0.587], [-0.757, 0, 0.587]]),
    "HF": ([9, 1], [[0, 0, 0], [0, 0, 0.917]]),
    "PH3": ([15, 1, 1, 1], [[0, 0, 0], [1.19, 0, 0.77], [-0.6, 1.03, 0.77], [-0.6, -1.03, 0.77]]),
    "H2S": ([16, 1, 1], [[0, 0, 0], [0.9686, 0, 0.9269], [-0.9686, 0, 0.9269]]),
    "HCl": ([17, 1], [[0, 0, 0], [0, 0, 1.2746]]),
    "HBr": ([35, 1], [[0, 0, 0], [0, 0, 1.41]]),
    "HI": ([53, 1], [[0, 0, 0], [0, 0, 1.609]]),
    "Cl2": ([17, 17], [[0, 0, 0], [0, 0, 1.988]]),
}

DRIVER = r'''
#include <cstdio>
#include <vector>
#include "scf_d.h"
#include "core_hamiltonian.h"
#include "energy_device.h"
#include "pwcct_device.h"
using namespace nvMolKit::semiempirical;
int main(){ int n; while(scanf("%d",&n)==1&&n>0){
  std::vector<int> z(n); std::vector<double> c(3*n);
  for(int a=0;a<n;++a) scanf("%d %lf %lf %lf",&z[a],&c[3*a],&c[3*a+1],&c[3*a+2]);
  std::vector<double> g(3*n); double E=0;
  if(!pm6dGradient(n,z.data(),c.data(),g.data(),&E,800,1e-10,1e-5)){ printf("0\n"); continue; }
  std::vector<AtomIntParams> ap(n); for(int a=0;a<n;++a) gatherAtomIntParamsD(z[a],ap[a]);
  double am1=nuclearRepulsionAm1Dev(n,ap.data(),c.data());
  printf("1 %.10f\n", (E-am1) + pwcctCoreCoreDev(n,z.data(),c.data())); // E_total = eElec + PWCCT
}
return 0;}
'''

HEADER = '''// SPDX-FileCopyrightText: Copyright (c) 2025 InsilicAll. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// GENERATED by tools/semiempirical/gen_pm6_hof_ref.py (calibrated against MOPAC
// 23.2.5 PM6) -- DO NOT HAND-EDIT.
//
// Per-element heat-of-formation reference for the canonical (MOPAC-aligned) PM6
// heat of formation: HoF(kcal) = kEvToKcal * (E_elec + E_core_PWCCT) - sum kHofRef.
// Each kHofRef[Z] = kEvToKcal*EISOL - EHEAT, fit by least squares so the simple
// hydrides reproduce MOPAC's FINAL HEAT OF FORMATION to <0.1 kcal/mol. With the
// PWCCT core-core (bit-exact to MOPAC) and the PYSEQM electronic SCF, the HoF then
// matches MOPAC PM6 to ~1 kcal/mol for light + Br molecules (iodine looser).

#ifndef NVMOLKIT_SEMIEMPIRICAL_PWCCT_REF_DATA_H
#define NVMOLKIT_SEMIEMPIRICAL_PWCCT_REF_DATA_H

#include "pwcct_data.h"  // kPwcctMaxZ

namespace nvMolKit {
namespace semiempirical {
namespace pwcct {

constexpr double kEvToKcal = 23.060548;

// kHofRef[Z] (kcal/mol); unsupported elements are 0.
constexpr double kHofRef[kPwcctMaxZ + 1] = {%(VALS)s};

}  // namespace pwcct
}  // namespace semiempirical
}  // namespace nvMolKit

#endif  // NVMOLKIT_SEMIEMPIRICAL_PWCCT_REF_DATA_H
'''


def main() -> int:
    mop = os.environ.get("MOPAC_DIR")
    if not mop or not (Path(mop) / "bin" / "mopac").is_file():
        sys.exit("set MOPAC_DIR to the unpacked mopac-*-linux dir (see module docstring)")
    env = dict(os.environ, LD_LIBRARY_PATH=f"{mop}/lib:" + os.environ.get("LD_LIBRARY_PATH", ""))

    def mopac_hof(Z, c):
        geo = "\n".join(f"{SYM[z]} {p[0]:.6f} 0 {p[1]:.6f} 0 {p[2]:.6f} 0" for z, p in zip(Z, c))
        Path("/tmp/_hofref.mop").write_text(f"PM6 1SCF CHARGE=0 PRECISE\nx\n\n{geo}\n")
        subprocess.run([f"{mop}/bin/mopac", "/tmp/_hofref.mop"], env=env, capture_output=True)
        for l in Path("/tmp/_hofref.out").read_text().splitlines():
            if "FINAL HEAT" in l:
                return float(l.split("=")[1].split("KCAL")[0])
        raise RuntimeError("no HoF from MOPAC")

    with tempfile.TemporaryDirectory() as td:
        cf = Path(td) / "drv.cpp"
        cf.write_text(DRIVER)
        exe = Path(td) / "drv"
        subprocess.run(["g++", "-std=c++17", "-O2", f"-I{SRC}", str(cf),
                        str(SRC / "core_hamiltonian.cpp"), str(SRC / "pm6_params.cpp"),
                        str(SRC / "overlap.cpp"), str(SRC / "scf_d.cpp"), "-o", str(exe)], check=True)
        names = list(CAL)
        stdin = []
        for nm in names:
            Z, c = CAL[nm]
            stdin.append(str(len(Z)))
            stdin += [f"{z} {p[0]:.10f} {p[1]:.10f} {p[2]:.10f}" for z, p in zip(Z, c)]
        out = subprocess.run([str(exe)], input="\n".join(stdin) + "\n",
                             capture_output=True, text=True).stdout.split("\n")

    rows = []
    for nm, line in zip(names, out):
        t = line.split()
        if t[0] != "1":
            sys.exit(f"engine did not converge for calibration molecule {nm}")
        rows.append((CAL[nm][0], float(t[1]), mopac_hof(*CAL[nm])))
    elems = sorted({e for Z, _, _ in rows for e in Z})
    A = np.array([[Z.count(e) for e in elems] for Z, _, _ in rows], float)
    y = np.array([CONV * T - hof for _, T, hof in rows])  # = sum_el n_el * kHofRef_el
    ref, *_ = np.linalg.lstsq(A, y, rcond=None)
    refmap = {e: r for e, r in zip(elems, ref)}
    resid = float(np.max(np.abs(y - A @ ref)))

    vals = []
    for z in range(54):
        v = float(refmap.get(z, 0.0))
        comment = f"  // {z} {SYM[z]}" if z in SYM else ""
        vals.append(f"    {v!r},{comment}")
    OUT.write_text(HEADER % {"VALS": "\n" + "\n".join(vals) + "\n"})
    print(f"wrote {OUT.relative_to(ROOT)}  (calib residual {resid:.3f} kcal); "
          f"ref={ {SYM[e]: round(r, 3) for e, r in refmap.items()} }")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
