"""Generate the baked one-center d two-electron W integrals + packing maps header.

The PM6_D one-center Fock d-block needs, per element, the 243 one-center d
two-electron integrals W plus the (element-independent) packing maps that fold
the 45 lower-triangle density products into the 45 Fock contributions. These were
frozen from PYSEQM into data/golden_w_onecenter_d.json (validated bit-exact by
tools/semiempirical/validate_pm6d.py). Rather than port PYSEQM's ~400-line
Slater-Condon _SC/_aijl/_poij machinery, the integrals are baked here as a C++
constant table, mirroring how pm6_params_data.h is generated from the CSV.

    python3 tools/semiempirical/gen_onecenter_d_header.py

Writes rocmolkit/src/semiempirical/onecenter_d_data.h (do not hand-edit).
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SRC = ROOT / "rocmolkit" / "src" / "semiempirical" / "onecenter_d_data.h"
DATA = Path(__file__).resolve().parent / "data" / "golden_w_onecenter_d.json"

HEADER = """// SPDX-FileCopyrightText: Copyright (c) 2025 InsilicAll. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// GENERATED by tools/semiempirical/gen_onecenter_d_header.py from
// data/golden_w_onecenter_d.json -- DO NOT HAND-EDIT.
//
// Baked one-center d two-electron integrals W (243 per element) and the
// element-independent packing maps that fold the 45 lower-triangle density
// products of a 9-orbital atom into its 45 one-center Fock contributions. The
// integrals were frozen from PYSEQM's pyseqm_d_params Slater-Condon code and
// validated bit-exact end-to-end by tools/semiempirical/validate_pm6d.py.

#ifndef NVMOLKIT_SEMIEMPIRICAL_ONECENTER_D_DATA_H
#define NVMOLKIT_SEMIEMPIRICAL_ONECENTER_D_DATA_H

#include "device_macros.h"  // NVMOLKIT_HD

namespace nvMolKit {
namespace semiempirical {
namespace onecenterd {

// 9x9 lower-triangle (mu>=nu) flattened indices, mu=TRIL_I[k], nu=TRIL_J[k].
constexpr int kNTril = 45;
"""

FOOTER = """
// Per-element one-center d two-electron integrals (243 each). Returns nullptr if
// z has no d parameters baked here.
NVMOLKIT_HD inline const double* oneCenterDW(int z) {
%(WSWITCH)s  return nullptr;
}

}  // namespace onecenterd
}  // namespace semiempirical
}  // namespace nvMolKit

#endif  // NVMOLKIT_SEMIEMPIRICAL_ONECENTER_D_DATA_H
"""


def fmt_ints(name: str, vals: list[int]) -> str:
    body = ", ".join(str(v) for v in vals)
    return f"constexpr int {name}[kNTril] = {{{body}}};\n"


def fmt_doubles(name: str, vals: list[float]) -> str:
    body = ", ".join(repr(float(v)) for v in vals)
    return f"constexpr double {name}[kNTril] = {{{body}}};\n"


def main() -> None:
    d = json.loads(DATA.read_text())
    m = d["maps"]
    TI, TJ, WT, FL = m["TRIL_I"], m["TRIL_J"], m["WEIGHT_45"], m["FLOCAL"]

    out = [HEADER]
    out.append(fmt_ints("kTrilI", TI))
    out.append(fmt_ints("kTrilJ", TJ))
    out.append(fmt_doubles("kWeight45", WT))

    # FLOCAL: 45 entries, each (col, wis[], pis[]) with variable length. Flatten
    # into a CSR-style layout: kFlCol[45], kFlOff[46], kFlWi[N], kFlPi[N].
    cols = [e[0] for e in FL]
    off = [0]
    wi: list[int] = []
    pi: list[int] = []
    for _, wis, pis in FL:
        wi.extend(wis)
        pi.extend(pis)
        off.append(len(wi))
    out.append("\n// FLOCAL folded as CSR: entry k contributes to Fock element\n")
    out.append("// (kTrilI[kFlCol[k]], kTrilJ[kFlCol[k]]) the sum over kFlOff[k]..kFlOff[k+1]\n")
    out.append("// of W[kFlWi[t]] * Pp[kFlPi[t]], where Pp[j] = P[i,j]*kWeight45[j].\n")
    out.append(f"constexpr int kFlN = {len(wi)};\n")
    out.append("constexpr int kFlCol[kNTril] = {%s};\n" % ", ".join(str(c) for c in cols))
    out.append("constexpr int kFlOff[kNTril + 1] = {%s};\n" % ", ".join(str(c) for c in off))
    out.append("constexpr int kFlWi[kFlN] = {%s};\n" % ", ".join(str(c) for c in wi))
    out.append("constexpr int kFlPi[kFlN] = {%s};\n" % ", ".join(str(c) for c in pi))

    # Per-element W (243 each).
    wswitch = []
    for zk, vals in d["W"].items():
        z = int(zk)
        body = ", ".join(repr(float(v)) for v in vals)
        out.append(f"\nconstexpr double kW{z}[243] = {{{body}}};\n")
        wswitch.append(f"  if (z == {z}) return kW{z};")

    # Per-element J/K split for the open-shell (UHF) path: W = W_J - W_Kfold.
    # W_J[j] = intg[rep] (pure Coulomb, contracts with the total density);
    # W_Kfold[j] = 1/4*(intg[rf1]+intg[rf2]) (exchange). The UHF d Fock is
    #   F^sigma = sum W_J * Pp_total  -  2 * sum W_Kfold * Pp_sigma,
    # which reduces to the closed-shell W (Pp_sigma = Pp_total/2). Validated
    # bit-exact to the oracle compute_w_integrals (W reproduced to ~1e-15).
    if "W_J" in d and "W_Kfold" in d:
        jswitch, kswitch = [], []
        for zk in d["W_J"]:
            z = int(zk)
            bj = ", ".join(repr(float(v)) for v in d["W_J"][zk])
            bk = ", ".join(repr(float(v)) for v in d["W_Kfold"][zk])
            out.append(f"\nconstexpr double kWJ{z}[243] = {{{bj}}};\n")
            out.append(f"constexpr double kWK{z}[243] = {{{bk}}};\n")
            jswitch.append(f"  if (z == {z}) return kWJ{z};")
            kswitch.append(f"  if (z == {z}) return kWK{z};")
        out.append(
            "\n// Coulomb-only W_J (* total density) for the UHF one-center d Fock.\n"
            "NVMOLKIT_HD inline const double* oneCenterDWJ(int z) {\n"
            + "\n".join(jswitch) + "\n  return nullptr;\n}\n")
        out.append(
            "\n// Exchange W_Kfold (UHF uses 2x * the same-spin density) for the d Fock.\n"
            "NVMOLKIT_HD inline const double* oneCenterDWK(int z) {\n"
            + "\n".join(kswitch) + "\n  return nullptr;\n}\n")

    out.append(FOOTER % {"WSWITCH": "\n".join(wswitch)})
    SRC.write_text("".join(out))
    print(f"wrote {SRC.relative_to(ROOT)}  ({len(d['W'])} elements, kFlN={len(wi)})")


if __name__ == "__main__":
    main()
